### ISSUE TITLE
Database connection error

### ISSUE THREAD

**Issue by Kushelbek** [over12/oc-techmobi-multidb#1]
Hello!
After install and config your plugin i'm have an error:
![image](https://user-images.githubusercontent.com/13330003/109108162-0b89e500-7744-11eb-9c2c-07c7fca0ca78.png)

What i'm need to do to fix it?

Thank you!

Laravel Framework 6.18.43
OctoberCMS 471

**Comment by phpiando** [comment]
Hello @Kushelbek!

By the error message I believe that the database.php file change was missing..
[Click here to see the configuration](https://github.com/over12/oc-techmobi-multidb#configuring-file-databasephp)

If you need anything, I'm at your disposal

**Comment by Kushelbek** [comment]
@over12, i'll modify database.php look like your documentation, now my database.php like this:
```

    'original' => env('DB_CONNECTION', 'mysql'),

    'connections' => [
...

        'mysql' => [
            'driver'     => 'mysql',
            'engine'     => 'InnoDB',
            'host'       => env('MULTIDB_HOST', 'localhost'),
            'port'       => env('MULTIDB_PORT', 3306),
            'database'   => env('MULTIDB_DATABASE', 'my_db'),
            'username'   => env('MULTIDB_USERNAME', 'my_user'),
            'password'   => env('MULTIDB_PASSWORD', 'my_pwd'),
            'charset'    => 'utf8mb4',
            'collation'  => 'utf8mb4_unicode_ci',
            'prefix'     => '',
            'varcharmax' => 191,
        ],
...
]

```

But I am getting the error which is above in the screenshot.
Thank you!

**Comment by Kushelbek** [comment]
@over12 i'll find mistake.
I'm add new array:
```

'multidb' => [
        'driver' => 'mysql',
        'engine' => 'InnoDB',
        'host' => env('MULTIDB_HOST', 'localhost'),
        'port' => env('MULTIDB_PORT', 3306),
        'database' => env('MULTIDB_DATABASE', 'my_db'),
        'username' => env('MULTIDB_USERNAME', 'my_user'),
        'password' => env('MULTIDB_PASSWORD', 'my_pwd'),
        'charset' => 'utf8mb4',
        'collation' => 'utf8mb4_unicode_ci',
        'prefix' => '',
        'varcharmax' => 191,
    ],
```
Now DB can created, but i have a new error:
![image](https://user-images.githubusercontent.com/13330003/109123541-04220600-775b-11eb-9a0d-004c2373694b.png)

How can i fix it? Why plugin don't create a **backend_users** table?
Thank you.

**Comment by Kushelbek** [comment]
@over12 and i'll have second error with arror above:
![image](https://user-images.githubusercontent.com/13330003/109152045-02b50580-777c-11eb-8ca7-0855c833700a.png)

**Comment by phpiando** [comment]
@Kushelbek Hi, show me the script settings screen, please.
From the message he is trying to access the "core" table.

**Comment by Kushelbek** [comment]
@over12 Hi, i'll try to add to multidb Rainlab Blog plugin.
**Screen from my config\database.php:**
![image](https://user-images.githubusercontent.com/13330003/109301064-6efd3b00-7848-11eb-8028-2dc6721c54b1.png)
**Screen from my rainlab\blog\models\Category.php**
![image](https://user-images.githubusercontent.com/13330003/109300876-30678080-7848-11eb-8cbb-98943eb6e3d1.png)
**Screen from my rainlab\blog\models\Post.php**
![image](https://user-images.githubusercontent.com/13330003/109300925-41b08d00-7848-11eb-9632-7fe4494420db.png)

**Comment by Kushelbek** [comment]
@over12 i'm think, when create second or other DB we need to copy backend_users table with all user, who can CRUD.

**Comment by phpiando** [comment]
@Kushelbek Just a detail, maybe I didn’t make this easy in the Readme, and that was my mistake that I’m going to update.
You need to go to Settings -> MultiDB -> Settings and add your new plugin as enabled, then you need to go to Settings -> MultiDB -> MultiDB Hosts and click on the "Update all schemas" button.

Every time you make a change to migration or something like that, you need to go to the MultiDB plugin settings and click on the "Update All Schemas" button, I haven't done anything "automatic" yet to identify new versions of the plugins that have been queued , this is an improvement for the future.

**Comment by Kushelbek** [comment]
> @Kushelbek Just a detail, maybe I didn’t make this easy in the Readme, and that was my mistake that I’m going to update.
> You need to go to Settings -> MultiDB -> Settings and add your new plugin as enabled, then you need to go to Settings -> MultiDB -> MultiDB Hosts and click on the "Update all schemas" button.
> 
> Every time you make a change to migration or something like that, you need to go to the MultiDB plugin settings and click on the "Update All Schemas" button, I haven't done anything "automatic" yet to identify new versions of the plugins that have been queued , this is an improvement for the future.

It's not help. 
I'll fix error above by add to models/Domain.php:

    public function afterSave()
    {
        SyncDB::instance()->startSyncDB($this);
        
        $dbName = $this->db_name;
        
        DB::statement('CREATE TABLE '.$dbName.'.backend_users LIKE my_parent_bd_name.backend_users');
        DB::statement('INSERT '.$dbName.'.backend_users SELECT * FROM my_parent_bd_name.backend_users');
    }

I'm think need to updated classes/UpdateManager.php for auto updating backend_users table in child db.

After i'll fix this error i cant upload image. Ill updated rainlab blog post model like this:

class Post extends Model
{
        use \October\Rain\Database\Traits\Validation;
	use \Techmobi\Multidb\Traits\UsesMultiConnection;

	...
       
         public $attachMany = [
        'featured_images' => ['Techmobi\Multidb\Models\File', 'order' => 'sort_order'],
        'content_images'  => ['Techmobi\Multidb\Models\File']
         ];
    ...
}

but it not work :(
How can i'm add images?
Thank you!

**Comment by phpiando** [comment]
@Kushelbek I recorded a video where I installed a new instance of october and used a plugin that I made as an example of banner management.
Maybe in the video it exemplifies the way the settings are, anything tell me.

https://drive.google.com/file/d/1MSIVOg03uRcgAZaNrVEy-089QPdU709Q/view

**Comment by Kushelbek** [comment]
> @Kushelbek I recorded a video where I installed a new instance of october and used a plugin that I made as an example of banner management.
> Maybe in the video it exemplifies the way the settings are, anything tell me.
> 
> https://drive.google.com/file/d/1MSIVOg03uRcgAZaNrVEy-089QPdU709Q/view

Hello @over12! I'll do look like your video. But i can't attach image viaRainlab Blog.
I'll use your documentation and make like this:

```
class Post extends Model
{
use \October\Rain\Database\Traits\Validation;
use \Techmobi\Multidb\Traits\UsesMultiConnection;

other_code_here

     public $attachMany = [
    'featured_images' => ['Techmobi\Multidb\Models\File', 'order' => 'sort_order'],
    'content_images'  => ['Techmobi\Multidb\Models\File']
     ];

other_code_here

}
```
but this construction it not work :(
How can i'm add images?
Thank you!

**Comment by Kushelbek** [comment]
Hi @over12 , i'm fix error with image.
Add rule in .htaccess
